### ISSUE TITLE
Админы тоже люди

### ISSUE THREAD

**Issue by arku31** [ZolotukhinVM/project04.loftschool#3]
https://github.com/ZolotukhinVM/project04.loftschool/blob/master/app/Http/Controllers/OrderController.php#L20

Такие вещи обычно делают в двух экземплярах. Один для юзера. Админ - тоже юзер, он тоже может делать покупки в магазине (личные). А adminspace, это отдельный раздел, где админ может посмотреть всё взглядом админа :)

**Comment by ZolotukhinVM** [comment]
Исправлено.
